### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by HCAWN** [theTaikun/plotrock#4]
I get this error when installing.
Windows 10
blender 2.93.3

Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.93\2.93\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
ModuleNotFoundError: No module named 'plotrock-0'

What other information can I share to help diagnose this?

**Comment by theTaikun** [comment]
First off, thank you for being my first ever new issue poster!

Now, I can confirm your error and reproduce it. It is a problem with the way GitHub works, and I'll reorganize my repo in the next release to fix the problem.

For now, the easiest way to fix it is to rename the unzipped folder that blender installed in your `addons` folder from `plotrock-0-0-1` to simply `plotrock`

**Comment by theTaikun** [comment]
Fixed by adding a new zip file to the [v0.0.1 release](https://github.com/theTaikun/plotrock/releases/tag/v0.0.1) and updated install instructions
